"""Embed test/golden/*.json into test/golden_cases.g.dart.

A browser test cannot read files from disk, so the web run of the golden
harness uses this generated copy. golden_test.dart fails if the copy is stale.

    python tool/embed_goldens.py
"""
import glob
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = [
    "// GENERATED by tool/embed_goldens.py from test/golden/*.json. Do not edit.",
    "// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars",
    "",
    "const Map<String, String> embeddedGoldens = {",
]
count = 0
for path in sorted(glob.glob(os.path.join(ROOT, "test", "golden", "*.json"))):
    with open(path, encoding="utf-8") as fh:
        doc = json.load(fh)
    raw = json.dumps(doc, ensure_ascii=False)
    assert "'''" not in raw
    count += 1
    out.append(f"  {json.dumps(doc['calculator'])}: r'''{raw}''',")
out.append("};")
out.append("")
with open(os.path.join(ROOT, "test", "golden_cases.g.dart"), "w", encoding="utf-8") as fh:
    fh.write("\n".join(out))
print("embedded", count, "golden files")
